### ISSUE TITLE
Not working every time

### ISSUE THREAD

**Issue by manix** [MichelVos/rpi_cpu_infoscreen#2]
Hello and thanks for sharing this code!

We are using it in our project, however we experience a weird behavior. It does not work every time? When we spam the command like 5 times the text eventually shows up on the screen, and sometimes it does on the first try as expected. Sometimes running the same command twice will first show the text and then clear the screen, but other times the text remains no matter how many times we run the same command.

We need to use it programmatically and since we can not get a constant output you can see how this is a problem for us.

Can you suggest what might be the root of this? We will provide any information required!

**Comment by MichelVos** [comment]
Sorry for the delay. I just checked out my code and used it for a while. It seems to be ok. But sometimes the display looks a bit garbled. I will look into that. How are you using this? Do you have a script you are using? What hardware are you using?

**Comment by MichelVos** [comment]
Added a small test script that updates the screen every second. Please try it.

**Comment by MichelVos** [comment]
In this latest commit a small delay is added to the reset signal this might solve the issue. Please let me know.

**Comment by manix** [comment]
It has been a while. Since we couldn't get reliable output we decided to drop the display from our project and use a phone app instead. Unfortunately I can't give you feedback anymore, my apologies.
