### ISSUE TITLE
cant run test_bcm8544

### ISSUE THREAD

**Issue by joeyjo33** [MichelVos/rpi_cpu_infoscreen#3]
everytime i try to run the file test_bcm8544 i get the error:
-bash: test_bcm8544: command not found

i also tried to run the hello world example in the README.md, it gives this error:
-bash: test_bcm8544: command not found

am i doing something wrong?
please help

**Comment by MichelVos** [comment]
Did you compile it?
Did you add the ./ before the command. See in linux a command is searched for in the PATH but the PATH does not contain the current directory. So please try   ./test_bcm8544

Hope this helps

**Comment by joeyjo33** [comment]
thanks for the response but i somehow figured it out myself so this thread
can be closed

Op zo 25 sep. 2022 07:34 schreef Michel Vos ***@***.***>:

**Comment by MichelVos** [comment]
thanks for the response but i somehow figured it out myself so this thread
can be closed
